// Generated by CoffeeScript 1.3.3
(function() {
  var addTrades, initialURL, notifications_sample, popped, removeTrades, viewTrade, viewTrades;

  $('#search input').typeahead({
    source: ['Scorch Shot', 'Flare Gun', 'Fire Axe']
  });

  $('.top-var-nav li a').tooltip({
    placement: 'bottom'
  });

  addTrades = function(query, push) {
    if (history.pushState && push) {
      history.pushState(null, null, "search/" + query);
    }
    return $.get("/search.json", function(data) {
      $(".trades").append('eco stuff');
      $(".item a").tooltip({
        placement: "bottom"
      });
      return $("#search-results").slideDown(400);
    });
  };

  removeTrades = function() {
    $("#search-results").slideUp(400);
    return $(".trade").remove();
  };

  viewTrades = function(push) {
    if (push === undefined) {
      push = true;
    }
    if ($(".trade").length === 0) {
      document.title = $("#search_field").val() + " results on Treddit";
      addTrades($("#search_field").val(), push);
    } else {
      removeTrades();
      document.title = $("#search_field").val() + " results on Treddit";
      addTrades($("#search_field").val(), push);
    }
    return false;
  };

  $('.search btn').click(viewTrades);

  viewTrade = function(n, push) {
    if (history.pushState && push) {
      history.pushState(null, null, "/trade/" + $(".trade:nth-child(" + n + ")").data("trade-id"));
    }
    $(".hero-search").css("left", "-101%");
    return $("#search-results").slideUp(function() {
      $(".trade:not(:nth-child(" + n + "))").css("display", "none");
      $(".trade:nth-child(" + n + ") .trade-div").after('eco stuff');
      $("#search-results").addClass("all-round");
      return $("#search-results").css("margin-top", "-" + $(".hero-search").outerHeight() + "px").slideDown();
    });
  };

  notifications_sample = {
    notifications: [
      {
        notification_text: "Foo has barred!"
      }, {
        notification_text: "There's a new trade for the Huntsman!"
      }
    ]
  };

  popped = "state" in window.history;

  initialURL = location.href;

  $(window).bind("popstate", function(event) {
    var initialPop, urlParts;
    initialPop = !popped && location.href === initialURL;
    popped = true;
    if (initialPop) {
      return;
    }
    urlParts = window.location.pathname.split("/");
    if (urlParts.length === 2 && urlParts[0] === "search") {
      $("#search_field").val(unescape(urlParts[1]));
      return viewTrades(false);
    } else if (!(urlParts.length === 2 && urlParts[0] === "trade")) {
      document.title = "Treddit";
      $("#search_field").val("");
      return removeTrades();
    }
  });

  $("#search_field").submit(viewTrades);

  $(".form-search").submit(viewTrades);

  $("#notifications").popover({
    placement: "bottom",
    title: "Notifications",
    content: function() {
      return 'hi';
    },
    trigger: "manual"
  });

  $("#notifications").click(function() {
    $("#notifications").popover("toggle");
    return $("#notifications").tooltip("hide");
  });

  $(".trades").on("click", ".trade .expand a", function(event) {
    return viewTrade($(this).index() + 1, true);
  });

  setTimeout(5000, function() {
    return $(".hero-unit").width(0);
  });

}).call(this);
